# Generated by Django 2.0.6 on 2018-08-02 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cisterna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('escola', models.CharField(max_length=160)),
                ('status', models.BooleanField(default=False)),
                ('status_bomba', models.BooleanField(default=False)),
                ('litros', models.FloatField()),
                ('ultima_medicao', models.DateTimeField(verbose_name='ultima medicao')),
            ],
        ),
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(verbose_name='data da medicao')),
                ('litros', models.FloatField()),
                ('cisterna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cisternas.Cisterna')),
            ],
        ),
    ]
