# Generated by Django 2.0.6 on 2018-08-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisternas', '0002_auto_20180802_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cisterna',
            name='ultima_medicao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ultima medicao'),
        ),
    ]
