# Generated by Django 2.0.6 on 2018-08-16 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cisternas', '0003_auto_20180802_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicao',
            options={'ordering': ('time_stamp',)},
        ),
        migrations.RemoveField(
            model_name='cisterna',
            name='litros',
        ),
        migrations.RemoveField(
            model_name='cisterna',
            name='ultima_medicao',
        ),
        migrations.AddField(
            model_name='cisterna',
            name='capacidade',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='cisterna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='cisternas.Cisterna'),
        ),
    ]
